FROM resin/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -y python-pygame git

ENV INITSYSTEM on

ENV DEVICE %%RESIN_MACHINE_NAME%% 

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["bash", "/usr/src/app/start.sh"]